import { createClient } from '@supabase/supabase-js';
import { ScanRecord, Expedition, Courier, ReturnRecord, ShopeeProduct, Order } from '../types';
import { addToQueue } from './offlineQueue';

const supabaseUrl = (import.meta as any).env?.VITE_SUPABASE_URL || '';
const supabaseAnonKey = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || '';

export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey && supabaseUrl.includes('.supabase.co'));

export const supabase = isSupabaseConfigured
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

// SQL Script to create tables in Supabase SQL Editor
export const SUPABASE_SETUP_SQL = `-- 1. Table for Scan Records
CREATE TABLE IF NOT EXISTS public.verell_records (
    id TEXT PRIMARY KEY,
    resi TEXT NOT NULL,
    tanggal TEXT NOT NULL,
    time TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    status TEXT NOT NULL,
    expedition TEXT,
    "courierCode" TEXT,
    "noPesanan" TEXT,
    products JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table for Return Records
CREATE TABLE IF NOT EXISTS public.verell_returns (
    id TEXT PRIMARY KEY,
    resi TEXT NOT NULL,
    tanggal TEXT NOT NULL,
    time TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    "courierName" TEXT NOT NULL,
    condition TEXT NOT NULL, -- 'BAIK', 'RUSAK', 'TERBUKA'
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table for Cancelled Resi
CREATE TABLE IF NOT EXISTS public.verell_cancelled_resi (
    resi TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table for Expeditions
CREATE TABLE IF NOT EXISTS public.verell_expeditions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    prefix TEXT NOT NULL,
    types JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table for Couriers
CREATE TABLE IF NOT EXISTS public.verell_couriers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    vehicle TEXT NOT NULL,
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Table for Custom Shopee Map/Mappings
CREATE TABLE IF NOT EXISTS public.verell_shopee_mappings (
    resi TEXT PRIMARY KEY,
    "noPesanan" TEXT NOT NULL,
    products JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) and allow public read/write (since we use public anon keys)
-- Alternatively, turn off RLS for these tables to make it simple for public demo clients:
ALTER TABLE public.verell_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.verell_returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.verell_cancelled_resi DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.verell_expeditions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.verell_couriers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.verell_shopee_mappings DISABLE ROW LEVEL SECURITY;

-- Enable Realtime for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.verell_records;
ALTER PUBLICATION supabase_realtime ADD TABLE public.verell_returns;
ALTER PUBLICATION supabase_realtime ADD TABLE public.verell_cancelled_resi;
ALTER PUBLICATION supabase_realtime ADD TABLE public.verell_expeditions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.verell_couriers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.verell_shopee_mappings;

-- 7. Table for Orders (Shopee Packing Feature)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_pesanan TEXT UNIQUE NOT NULL,
    no_resi TEXT UNIQUE NOT NULL,
    nama_produk TEXT NOT NULL,
    harga NUMERIC NOT NULL DEFAULT 0,
    jumlah INTEGER NOT NULL DEFAULT 1,
    nama_penerima TEXT,
    alamat_pengiriman TEXT,
    kota TEXT,
    provinsi TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_no_resi ON public.orders (no_resi);

-- Enable RLS for orders table and add policies
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Allow public CRUD operations (insert, select, update) via anon key
CREATE POLICY "Allow public select of orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert of orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update of orders" ON public.orders FOR UPDATE USING (true) WITH CHECK (true);

-- Enable Realtime replication for orders
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
`;

// Helper types & operations to ensure uniform execution on Supabase
export const db = {
  async fetchAll() {
    if (!supabase) return null;
    try {
      const [
        { data: recs },
        { data: rets },
        { data: cancs },
        { data: exps },
        { data: curs },
        { data: maps }
      ] = await Promise.all([
        supabase.from('verell_records').select('*').order('timestamp', { ascending: false }),
        supabase.from('verell_returns').select('*').order('timestamp', { ascending: false }),
        supabase.from('verell_cancelled_resi').select('*'),
        supabase.from('verell_expeditions').select('*'),
        supabase.from('verell_couriers').select('*'),
        supabase.from('verell_shopee_mappings').select('*')
      ]);

      return {
        records: (recs || []) as ScanRecord[],
        returns: (rets || []) as ReturnRecord[],
        cancelledResi: (cancs || []).map(c => c.resi) as string[],
        expeditions: (exps || []) as Expedition[],
        couriers: (curs || []) as Courier[],
        shopeeMappings: (maps || []).reduce((acc, current) => {
          acc[current.resi] = {
            noPesanan: current.noPesanan,
            products: current.products as ShopeeProduct[]
          };
          return acc;
        }, {} as Record<string, { noPesanan: string; products: ShopeeProduct[] }>)
      };
    } catch (err) {
      console.error('Failed to fetch from Supabase:', err);
      throw err;
    }
  },

  // Records upsert/delete
  async upsertRecord(record: ScanRecord) {
    if (!supabase || !navigator.onLine) {
      console.log('[Offline] Device is offline, queueing ScanRecord:', record);
      await addToQueue('record', record);
      return;
    }
    try {
      const { error } = await supabase.from('verell_records').upsert({
        id: record.id,
        resi: record.resi,
        tanggal: record.tanggal,
        time: record.time,
        timestamp: record.timestamp,
        status: record.status,
        expedition: record.expedition || null,
        courierCode: record.courierCode || null,
        noPesanan: record.noPesanan || null,
        products: record.products || null
      });
      if (error) {
        if (error.code === '23505') {
          console.warn('[Supabase] First-write-wins duplicate blocked (record):', record.resi);
        } else {
          console.error('Supabase upsertRecord error, queueing...', error);
          await addToQueue('record', record);
        }
      }
    } catch (err) {
      console.warn('Supabase upsertRecord exception, queueing...', err);
      try {
        await addToQueue('record', record);
      } catch (idbErr) {
        console.error('Failed to write to IDB:', idbErr);
      }
    }
  },

  async deleteRecord(id: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_records').delete().eq('id', id);
    if (error) console.error('Supabase deleteRecord error:', error);
  },

  async deleteRecordByResi(resi: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_records').delete().eq('resi', resi);
    if (error) console.error('Supabase deleteRecordByResi error:', error);
  },

  async clearAllRecords() {
    if (!supabase) return;
    const { error } = await supabase.from('verell_records').delete().neq('id', 'placeholder-doesnotexist');
    if (error) console.error('Supabase clearAllRecords error:', error);
  },

  // Returns upsert/delete
  async upsertReturn(record: ReturnRecord) {
    if (!supabase || !navigator.onLine) {
      console.log('[Offline] Device is offline, queueing ReturnRecord:', record);
      await addToQueue('return', record);
      return;
    }
    try {
      const { error } = await supabase.from('verell_returns').upsert({
        id: record.id,
        resi: record.resi,
        tanggal: record.tanggal,
        time: record.time,
        timestamp: record.timestamp,
        courierName: record.courierName,
        condition: record.condition,
        reason: record.reason
      });
      if (error) {
        if (error.code === '23505') {
          console.warn('[Supabase] First-write-wins duplicate blocked (return):', record.resi);
        } else {
          console.error('Supabase upsertReturn error, queueing...', error);
          await addToQueue('return', record);
        }
      }
    } catch (err) {
      console.warn('Supabase upsertReturn exception, queueing...', err);
      try {
        await addToQueue('return', record);
      } catch (idbErr) {
        console.error('Failed to write to IDB Return:', idbErr);
      }
    }
  },

  async deleteReturn(id: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_returns').delete().eq('id', id);
    if (error) console.error('Supabase deleteReturn error:', error);
  },

  async clearAllReturns() {
    if (!supabase) return;
    const { error } = await supabase.from('verell_returns').delete().neq('id', 'placeholder-doesnotexist');
    if (error) console.error('Supabase clearAllReturns error:', error);
  },

  // Cancelled Resi insert/delete
  async insertCancelledResi(resi: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_cancelled_resi').upsert({
      resi: resi
    });
    if (error) console.error('Supabase insertCancelledResi error:', error);
  },

  async deleteCancelledResi(resi: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_cancelled_resi').delete().eq('resi', resi);
    if (error) console.error('Supabase deleteCancelledResi error:', error);
  },

  async clearAllCancelledResi() {
    if (!supabase) return;
    const { error } = await supabase.from('verell_cancelled_resi').delete().neq('resi', 'placeholder-doesnotexist');
    if (error) console.error('Supabase clearAllCancelledResi error:', error);
  },

  // Expeditions upsert/delete
  async upsertExpedition(exp: Expedition) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_expeditions').upsert({
      id: exp.id,
      name: exp.name,
      prefix: exp.prefix,
      types: exp.types
    });
    if (error) console.error('Supabase upsertExpedition error:', error);
  },

  async deleteExpedition(id: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_expeditions').delete().eq('id', id);
    if (error) console.error('Supabase deleteExpedition error:', error);
  },

  async resetExpeditions(list: Expedition[]) {
    if (!supabase) return;
    // Clear first, then insert all
    await supabase.from('verell_expeditions').delete().neq('id', 'placeholder-doesnotexist');
    for (const exp of list) {
      await this.upsertExpedition(exp);
    }
  },

  // Couriers upsert/delete
  async upsertCourier(cur: Courier) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_couriers').upsert({
      id: cur.id,
      name: cur.name,
      phone: cur.phone,
      vehicle: cur.vehicle,
      code: cur.code
    });
    if (error) console.error('Supabase upsertCourier error:', error);
  },

  async deleteCourier(id: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_couriers').delete().eq('id', id);
    if (error) console.error('Supabase deleteCourier error:', error);
  },

  async resetCouriers(list: Courier[]) {
    if (!supabase) return;
    await supabase.from('verell_couriers').delete().neq('id', 'placeholder-doesnotexist');
    for (const cur of list) {
      await this.upsertCourier(cur);
    }
  },

  // Custom Shopee mappings upsert/delete
  async upsertShopeeMapping(resi: string, noPesanan: string, products: ShopeeProduct[]) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_shopee_mappings').upsert({
      resi,
      noPesanan,
      products
    });
    if (error) console.error('Supabase upsertShopeeMapping error:', error);
  },

  async deleteShopeeMapping(resi: string) {
    if (!supabase) return;
    const { error } = await supabase.from('verell_shopee_mappings').delete().eq('resi', resi);
    if (error) console.error('Supabase deleteShopeeMapping error:', error);
  },

  async clearAllShopeeMappings() {
    if (!supabase) return;
    const { error } = await supabase.from('verell_shopee_mappings').delete().neq('resi', 'placeholder-doesnotexist');
    if (error) console.error('Supabase clearAllShopeeMappings error:', error);
  }
};

/**
 * Upload packed orders from CSV data into Supabase orders table.
 * Automatically handles duplicates by checking against existing no_pesanan records.
 */
export async function uploadOrdersFromCSV(data: any[]): Promise<{
  success: boolean;
  inserted: number;
  skipped: number;
  error?: string;
}> {
  if (!supabase) {
    return { success: false, inserted: 0, skipped: data.length, error: 'Supabase client is not configured.' };
  }

  try {
    // 1. Fetch all existing order identifiers (no_pesanan) to check duplicates
    const { data: existing, error: fetchError } = await supabase
      .from('orders')
      .select('no_pesanan');

    if (fetchError) {
      return { success: false, inserted: 0, skipped: 0, error: 'Database fetch error: ' + fetchError.message };
    }

    const existingKeys = new Set((existing || []).map(o => String(o.no_pesanan).trim()));
    const seenInBatch = new Set<string>();
    const toInsert: Order[] = [];
    let skipped = 0;

    for (const row of data) {
      if (!row) {
        skipped++;
        continue;
      }

      // Keep normalize helper clean & highly adaptive to Indonesian Shopee template formats
      const no_pesanan = String(
        row.no_pesanan || 
        row['No. Pesanan'] || 
        row['No Pesanan'] || 
        row['noPesanan'] || 
        row['nomor_pesanan'] || 
        ''
      ).trim();

      const no_resi = String(
        row.no_resi || 
        row['No. Resi'] || 
        row['No Resi'] || 
        row['noResi'] || 
        row['nomor_resi'] || 
        ''
      ).trim();

      if (!no_pesanan || !no_resi) {
        skipped++;
        continue;
      }

      if (existingKeys.has(no_pesanan) || seenInBatch.has(no_pesanan)) {
        skipped++;
        continue;
      }

      seenInBatch.add(no_pesanan);

      const nama_produk = String(
        row.nama_produk || 
        row['Nama Produk'] || 
        row['namaProduk'] || 
        row['produk'] || 
        'Produk Tanpa Nama'
      ).trim();

      // Normalize numeric variables
      let harga = 0;
      const rawHarga = row.harga ?? row['Harga'] ?? row['Harga Satuan'] ?? row['harga_satuan'] ?? 0;
      if (typeof rawHarga === 'number') {
        harga = rawHarga;
      } else {
        harga = parseFloat(String(rawHarga).replace(/[^0-9.-]+/g, "")) || 0;
      }

      let jumlah = 1;
      const rawJumlah = row.jumlah ?? row['Jumlah'] ?? row['Qty'] ?? row['Quantity'] ?? row['quantity'] ?? 1;
      if (typeof rawJumlah === 'number') {
        jumlah = rawJumlah;
      } else {
        jumlah = parseInt(String(rawJumlah).replace(/[^0-9-]+/g, "")) || 1;
      }

      const nama_penerima = String(row.nama_penerima || row['Nama Penerima'] || row['Penerima'] || '').trim() || null;
      const alamat_pengiriman = String(row.alamat_pengiriman || row['Alamat Pengiriman'] || row['Alamat'] || '').trim() || null;
      const kota = String(row.kota || row['Kota'] || '').trim() || null;
      const provinsi = String(row.provinsi || row['Provinsi'] || '').trim() || null;

      toInsert.push({
        no_pesanan,
        no_resi,
        nama_produk,
        harga,
        jumlah,
        nama_penerima,
        alamat_pengiriman,
        kota,
        provinsi
      });
    }

    if (toInsert.length > 0) {
      const { error: insertError } = await supabase
        .from('orders')
        .insert(toInsert);

      if (insertError) {
        return { success: false, inserted: 0, skipped: data.length, error: 'Database insert error: ' + insertError.message };
      }
    }

    return {
      success: true,
      inserted: toInsert.length,
      skipped,
    };
  } catch (err: any) {
    console.error('Failed to upload systems orders:', err);
    return {
      success: false,
      inserted: 0,
      skipped: data.length,
      error: err.message || 'Unknown internal error'
    };
  }
}

/**
 * Retrieve a single order object by its tracking number (no_resi).
 */
export async function getOrderByResi(resi: string): Promise<Order | null> {
  if (!supabase) return null;
  try {
    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .eq('no_resi', resi)
      .maybeSingle();

    if (error) {
      console.error(`Error in getOrderByResi with key ${resi}:`, error);
      return null;
    }
    return data as Order | null;
  } catch (err) {
    console.error(`Exception in getOrderByResi with key ${resi}:`, err);
    return null;
  }
}

/**
 * Retrieve all orders ordered by creation date descending.
 */
export async function getAllOrders(): Promise<Order[]> {
  if (!supabase) return [];
  try {
    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error in getAllOrders:', error);
      return [];
    }
    return (data || []) as Order[];
  } catch (err) {
    console.error('Exception in getAllOrders:', err);
    return [];
  }
}

